version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 87654321
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
  rest-validator:
    container_name: rest-validator
    image: victormacedo400/rest-validator:v2
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    ports:
      - "3000:3000"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      -  rabbitmq-data:/var/lib/rabbitmq/

volumes:
  postgres-db:
    driver: local
  rabbitmq-data:
    driver: local
